name: DeployToGitHubPages
env:
  PUBLISH_DIR: ${{github.workspace}}/master/RadiocomDataViewApp/bin/Release/net5.0/publish/wwwroot
on:
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest
  

    steps:
    - name: Path
      run: |
        ls
        pwd
        
    - uses: actions/checkout@v2
      with:
        path: master
  
    - name: Path
      run: |
        ls
        pwd
    
    - name: Checkout gh-pages branch
      uses: actions/checkout@v2
      with:
        ref: gh-pages
        path: gh-pages
    
    - uses: FranzDiebold/github-env-vars-action@v2.1.0
    - name: GitHub Environment Variables Action
      run: |
          echo "CI_REPOSITORY_NAME=${CI_REPOSITORY_NAME}" >> $GITHUB_ENV
          echo "${{github.workspace}}"
          
    - name: Setup .NET
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: '5.0.x'
        
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: |
        dotnet build --no-restore 
    
    - name: Test
      run: dotnet test --no-build --verbosity normal
    
    - name: publish
      run: dotnet publish -c release
    
    - name: Nav
      run: |
        ls
#cd bin/release/net5.0/publish/wwwroot
        
    
    - name: Rewrite base href index.html
      uses: SteveSandersonMS/ghaction-rewrite-base-href@v1
      with:
        html_path: ${{ env.PUBLISH_DIR }}/index.html
        base_href: /${{ env.CI_REPOSITORY_NAME }}/
        
    #- name: Rewrite base href 404.html
    #  uses: SteveSandersonMS/ghaction-rewrite-base-href@v1
    #  with:
    #    html_path: ${{ env.PUBLISH_DIR }}/404.html
    #    base_href: /${{ env.CI_REPOSITORY_NAME }}/
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: RadiocomDataViewApp
        path: ${{ env.PUBLISH_DIR }}/
        if-no-files-found: error
    
    - name: Copy publish to gh-pages
      run: |
        ls ./gh-pages
        cp -a ${{env.PUBLISH_DIR}}/. ./gh-pages/
        git config user.name actions
        git config user.email actions@actions.com
        git add .
        git commit -m "Updating with latest"
        git push origin gh-pages
        
    
   
