name: .NET

on:
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: '5.0.x'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: publish
      run: dotnet publish -c release
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: RadiocomDataViewApp
        path: /home/runner/work/RadiocomDataViewApp/RadiocomDataViewApp/RadiocomDataViewApp/bin/Release/net5.0/publish/
        if-no-files-found: error
